### ISSUE TITLE
omits the dropdown item attribute

### ISSUE THREAD

**Issue by NileshPujari01** [alxlit/bootstrap-chosen#44]
Hi,
my dropdown items have two attributes,one is value and another is custom attribute "numeric". like shown below.
<option value="123" numeric="True">Primary home phone</option>
when dropdown gets value from database.<option> tag eliminates the numeric attributes and shows option tag like this.
<option selected="selected" value="642">Personal email</option>
because of this i am not able to retrieve the numeric attribute value.
how can i access my both attributes using this plugin when data coming from database and getting by SelectedValue proeprty. 
How can we resolve this?

**Comment by alxlit** [comment]
You probably mean to ask this in [chosen](https://github.com/harvesthq/chosen).

**Comment by NileshPujari01** [comment]
ohh.is it.sorry.

My mistake.

i'll post query there.

Thanks.
