### ISSUE TITLE
How to Compile

### ISSUE THREAD

**Issue by philipstratford** [alxlit/bootstrap-chosen#50]
I realise that posting here purely as a result of my ignorance must be really irritating, so forgive me, but I've spent hours on this already and I'm getting nowhere.

Before today I didn't really understand SASS or LESS. So, having decided to use SASS instead of LESS, I have downloaded Koala, a LESS and SASS compiler, downloaded the bootstrap-chosen.scss and bootstrap-chosen-variables.scss files from this repository and tried to compile them. I get an error about an undefined variable ($input-bg).

So, I've gone to the Bootstrap site, downloaded their .scss source files, and added _mixins.scss and _variables.scss into Koala too. Still I get the error.

I created my own .scss file in the same folder, which simply has an @import statement for each of the four downloaded .scss files. Still the error is thrown.

Given that I'm completely ignorant of how to compile SASS files, am not quite sure what I'm doing, don't quite understand the instruction "Just keep in mind that it needs access to variables.less and mixins.less." and am used to just working with pre-complied .css files... how can I simply get to the point where I have a .css file I can drop into my MVC5 project which will style Chosen controls to look like Bootstrap controls?

Would it be too onerous to include a pre-compiled .css file in the repository for people like me? What might I be doing wrong in trying to do this compiling myself?

Thanks!

**Comment by alxlit** [comment]
Phil,

Add these lines to the top of `bootstrap-chosen.scss`, replacing `path/to/` with wherever those files actually exist on your filesystem:
```
@import "path/to/_mixins.scss";
@import "path/to/_variables.scss";
```
I don't have time to precompile it right now. If you put together pull request, I'll gladly accept it.

**Comment by antonmaximus** [comment]
@philipstratford , You can use this instead: https://github.com/dbtek/chosen-bootstrap. 
This is the css version of the less/sass files you were trying to use.
