### ISSUE TITLE
Code Not Working Css Missing

### ISSUE THREAD

**Issue by bhallaheemanshu** [alxlit/bootstrap-chosen#56]
I directly download the code and run the Index filer but its missing css features and due to that bootstrap-choosen is also not working

**Comment by alxlit** [comment]
Please rewrite your description. I have no idea what you're talking about.
> I directly download the code and run the Index filer but its missing css features and due to that bootstrap-choosen is also not working

**Comment by alxlit** [comment]
See #57.

**Comment by bhallaheemanshu** [comment]
I fixed the missing css and made pull request regarding this

**Comment by dkhlystov** [comment]
It will be nice if you make release with this changes
