### ISSUE TITLE
how to clear the boostrap choosen data

### ISSUE THREAD

**Issue by suryamuppalla** [alxlit/bootstrap-chosen#62]
![screenshot from 2015-12-03 07 57 33](https://cloud.githubusercontent.com/assets/8057105/11550236/98164048-9993-11e5-80d4-961ec96d9b52.png)

I want to clear the another select data when i change the previous select option

thanks

**Comment by alxlit** [comment]
I do not think this issue belongs here (unless I misunderstood), try: https://github.com/harvesthq/chosen/issues
