### ISSUE TITLE
onchange event not supporting for jquery call

### ISSUE THREAD

**Issue by mailofpravin** [alxlit/bootstrap-chosen#63]
I was practicing ajax and decided to do a demo. I notice problem the actual html select jquery is not working after integrating chosen bootstrap.
              	<form:select id="country" path="country" data-placeholder="Choose a Country" class="chosen-select">
<form:options items="${countryNames}" />

I loaded my country select combo dynamically, I wanted to load cities based on country selection

in ajax, I used
$('#country').change(function(){
	alert("cities changed!!!");
});

I further tried it with changing the id to 
$('#country_chosen').change(function(){
	alert("cities changed!!!");
});

yet not working.

**Comment by alxlit** [comment]
Please read the documentation: http://harvesthq.github.io/chosen/#change-update-events
